"use client";

import { useTransition, useState } from "react";
import {
  Receipt,
  User,
  CreditCard,
  CheckCircle2,
  AlertCircle,
  MoreVertical,
  Search,
  Filter,
  ChevronDown,
  ArrowUpRight,
  ShieldCheck
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { updatePaymentStatusAction } from "@/actions/Billing/index";
import { toast } from "sonner";
import { format } from "date-fns";

interface Bill {
  _id: string;
  patientName: string;
  totalAmount: number;
  paymentStatus: "PENDING" | "PAID" | "OVERDUE";
  paymentMethod: "CASH" | "CARD" | "INSURANCE";
  billDate: string;
}

interface AdminBillingClientProps {
  initialBills: Bill[];
}

export default function AdminBillingClient({ initialBills }: AdminBillingClientProps) {
  const [isPending, startTransition] = useTransition();
  const [searchQuery, setSearchQuery] = useState("");

  const handleUpdateStatus = (billId: string, status: "PAID" | "OVERDUE") => {
    startTransition(async () => {
      const result = await updatePaymentStatusAction(billId, status);
      if (result.error) {
        toast.error(result.error);
      } else {
        toast.success(result.message);
      }
    });
  };

  const filteredBills = initialBills.filter(
    (b) =>
      b.patientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      b._id.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-fade-in max-w-(--breakpoint-2xl) mx-auto">
      
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Billing Management</h1>
          <p className="text-muted-foreground mt-1">Review and process all hospital financial transactions.</p>
        </div>
        <div className="flex items-center gap-3">
           <div className="relative w-full md:w-64">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Search patient or ID..." 
                className="pl-9 h-10 border-border bg-card shadow-sm"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
           </div>
           <Button className="bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-lg shadow-primary/20">
              Generate Report
           </Button>
        </div>
      </div>

      {/* Main Billing Table */}
      <Card className="shadow-sm border-border overflow-hidden rounded-2xl">
        <CardHeader className="bg-muted/30 border-b border-border px-6 py-5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                 <Receipt size={20} />
              </div>
              <div>
                <CardTitle className="text-lg font-bold">Financial Ledger</CardTitle>
                <CardDescription>All invoices generated by doctors and pharmacists.</CardDescription>
              </div>
            </div>
            <div className="flex items-center gap-2">
               <Button variant="outline" size="sm" className="h-9 border-border text-xs font-bold gap-1.5 px-3">
                  Status <ChevronDown size={14} />
               </Button>
               <Button variant="outline" size="sm" className="h-9 border-border text-xs font-bold gap-1.5 px-3">
                  <Filter size={14} /> Sort
               </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/10 hover:bg-muted/10">
                <TableHead className="w-[250px] font-bold text-[10px] uppercase tracking-widest px-6 py-3">Patient / Client</TableHead>
                <TableHead className="font-bold text-[10px] uppercase tracking-widest py-3">Amount</TableHead>
                <TableHead className="font-bold text-[10px] uppercase tracking-widest py-3 text-center">Payment Status</TableHead>
                <TableHead className="font-bold text-[10px] uppercase tracking-widest py-3">Method</TableHead>
                <TableHead className="text-right font-bold text-[10px] uppercase tracking-widest px-6 py-3">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredBills.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} className="h-64 text-center text-muted-foreground">
                    <Receipt className="mx-auto h-12 w-12 mb-3 opacity-10" />
                    <p className="font-medium italic">No billing records found in the system.</p>
                  </TableCell>
                </TableRow>
              ) : (
                filteredBills.map((bill) => (
                  <TableRow key={bill._id} className="group hover:bg-muted/30 transition-colors">
                    <TableCell className="px-6 py-4">
                      <div className="flex items-center gap-4">
                         <div className="h-9 w-9 rounded-full bg-slate-100 flex items-center justify-center text-slate-500 border border-slate-200 shadow-sm shrink-0">
                            <User size={16} />
                         </div>
                         <div className="min-w-0">
                            <p className="font-bold text-foreground text-sm truncate">{bill.patientName}</p>
                            <p className="text-[10px] text-muted-foreground font-medium uppercase tracking-tighter">
                                ID: {bill._id.slice(-8).toUpperCase()} • {format(new Date(bill.billDate), "dd MMM")}
                            </p>
                         </div>
                      </div>
                    </TableCell>
                    <TableCell className="py-4">
                        <div className="text-sm font-black text-foreground">
                            $ {bill.totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                        </div>
                    </TableCell>
                    <TableCell className="py-4 text-center">
                        <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-tight border ${
                            bill.paymentStatus === "PAID" 
                                ? "bg-success/10 text-success border-success/20" 
                                : bill.paymentStatus === "OVERDUE"
                                ? "bg-destructive/10 text-destructive border-destructive/20"
                                : "bg-warning/10 text-warning border-warning/20"
                        }`}>
                           <span className={`h-1.5 w-1.5 rounded-full ${
                               bill.paymentStatus === "PAID" ? "bg-success" : 
                               bill.paymentStatus === "OVERDUE" ? "bg-destructive" : "bg-warning"
                           }`} />
                           {bill.paymentStatus}
                        </span>
                    </TableCell>
                    <TableCell className="py-4">
                        <div className="flex items-center gap-2 text-[10px] font-bold text-muted-foreground uppercase">
                           <CreditCard size={12} /> {bill.paymentMethod}
                        </div>
                    </TableCell>
                    <TableCell className="text-right px-6 py-4">
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" className="h-9 w-9 text-muted-foreground border border-transparent hover:border-border hover:bg-muted">
                              <MoreVertical className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end" className="w-48 p-1.5 shadow-xl border-border bg-card">
                            <DropdownMenuItem 
                              className="text-success cursor-pointer font-bold text-xs flex items-center gap-2 p-2 rounded-md"
                              onClick={() => handleUpdateStatus(bill._id, "PAID")}
                              disabled={isPending || bill.paymentStatus === "PAID"}
                            >
                              <CheckCircle2 className="h-4 w-4" /> Confirm Payment
                            </DropdownMenuItem>
                            <DropdownMenuItem 
                              className="text-destructive cursor-pointer font-bold text-xs flex items-center gap-2 p-2 rounded-md"
                              onClick={() => handleUpdateStatus(bill._id, "OVERDUE")}
                              disabled={isPending || bill.paymentStatus === "PAID"}
                            >
                              <AlertCircle className="h-4 w-4" /> Mark Overdue
                            </DropdownMenuItem>
                            <div className="h-px bg-border my-1.5" />
                            <DropdownMenuItem className="cursor-pointer font-bold text-xs flex items-center gap-2 p-2 hover:bg-muted rounded-md">
                              <ArrowUpRight size={14} /> View Details
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      
      <div className="flex items-center gap-3 p-4 rounded-2xl bg-success/5 border border-success/10">
         <ShieldCheck className="h-5 w-5 text-success shrink-0" />
         <p className="text-xs font-medium text-success leading-tight">
            Payments confirmed here will be reflected in real-time in the patient&apos;s dashboard and the hospital&apos;s financial analytics.
         </p>
      </div>
    </div>
  );
}
